Do not bind on tmpsocket early
Since change I8f566543c8da28eb7ed76f1cb80ff4cb2dcbba96 openstackbmc has
failed to start with the error:

  socket.error: [Errno 22] Invalid argument

Backing out the change which does an early bind on the tmpsocket has
fixed the regression for openstackbmc.

Change-Id: Icb16cdc386fb08b54f28b7dff235eb697f1450ee