Check for buffer and use memoryview if missing
Python 3 does not implement buffer.  Use memoryview
as a standin if buffer would induce a NameError.

Change-Id: Id36e8253fffee9dc22bd982e00554f1c25bc95b4